version: "3"
services:
  react-app:
    image: react-app
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./backend/
    ports:
      - "4000:4000"
    networks:
      - mern-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes: 
  mongo-data:
    driver: local